# Generated by Django 4.1 on 2022-08-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('INN', models.CharField(max_length=600)),
                ('FIRMA', models.CharField(max_length=600)),
                ('SUMDA', models.CharField(blank=True, max_length=600)),
                ('KURS', models.CharField(blank=True, max_length=600)),
                ('DOLLAR', models.CharField(blank=True, max_length=600)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CLIENT', models.CharField(blank=True, max_length=600)),
                ('REGION', models.CharField(blank=True, max_length=600)),
                ('MANAGER', models.CharField(blank=True, max_length=600)),
            ],
        ),
    ]
