# Generated by Django 4.1 on 2022-08-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='DATE',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
