# Generated by Django 4.1 on 2022-08-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_person_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='ExeltoData',
        ),
    ]
