# Generated by Django 4.1 on 2022-08-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_person_exeltodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('DATE', models.CharField(blank=True, max_length=601)),
                ('INN', models.CharField(max_length=600)),
                ('FIRMA', models.CharField(max_length=600)),
                ('SUMDA', models.CharField(blank=True, max_length=600)),
                ('KURS', models.CharField(blank=True, max_length=600)),
                ('DOLLAR', models.CharField(blank=True, max_length=600)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CLIENT', models.CharField(blank=True, max_length=600)),
                ('REGION', models.CharField(blank=True, max_length=600)),
                ('MANAGER', models.CharField(blank=True, max_length=600)),
            ],
            options={
                'verbose_name': 'All Data',
                'verbose_name_plural': 'All Data',
            },
        ),
        migrations.AlterModelOptions(
            name='exeltodata',
            options={'verbose_name': 'Exel To Data', 'verbose_name_plural': 'Exel To Data'},
        ),
    ]
